# Generated by Django 5.2.16 on 2026-09-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='theme',
            field=models.CharField(choices=[('utn', 'UTN'), ('utnarm', 'Utnarm'), ('td', 'Teknolog- och datavetarmottagningen'), ('klubbverket', 'Klubbverket'), ('forsranningen', 'Forsränningen'), ('rebusrallyt', 'Rebusrallyt'), ('miljogruppen', 'Miljögruppen')], default='utn', help_text='Which theme to apply to the organisation.', max_length=20, verbose_name='theme'),
        ),
    ]
